language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add lerna
  - yarn install
  - yarn build-dev-utils
  - yarn install --force

script:
  - yarn build
  - yarn typecheck
  - yarn lint
  - yarn test -i --coverage
  - npm install codecov -g
after_success:
  - codecov
