language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add lerna
  - yarn install
  - lerna run build --scope @react-md/dev-utils
  - yarn install --force

script:
  - yarn build --silent
  - yarn workspace documentation sandbox --empty --silent
  - yarn typecheck
  - yarn lint
  - yarn test --runInBand
